#!/usr/bin/env node

var assert = require('./index');

assert.fatal = false;

// TODO make testable

assert(1);
assert.not('');
assert.eq([1,2,3], [1,2,3]);
assert.neq([1,2,3], [3,2,1]);
assert.is(1 + 2 + 3, 3 + 2 + 1);
assert.isnt([1,2,3], [1,2,3]);

try {
//	assert.is(1, 2);
//	assert.is(2, 3);
} catch (e) {
	console.log("Got exception");
	console.log(e);
}

assert.type("hello", 'string');
assert.type(1234, 'number');
assert.type({ a: 'b' }, 'object');
assert.type([1,2,3], 'object');
assert.type(function() {}, 'function');

// This will fail.
assert.eq([1,2,3], [1,2,3,4]);
